replicaCount: 3

workload:
  kind: Rollout

image:
  tag: "lab12"

env:
  APP_NAME: devops-info-service
  APP_DESCRIPTION: Canary rollout with analysis
  APP_VERSION: 2.0.0-canary-analysis
  APP_VARIANT: canary-analysis

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

rollout:
  strategy:
    type: canary
    blueGreen:
      autoPromotionEnabled: false
  analysis:
    enabled: true
    path: /health
