replicaCount: 3

workload:
  kind: StatefulSet

image:
  tag: "lab12"

env:
  APP_NAME: devops-info-service
  APP_DESCRIPTION: StatefulSet OnDelete update strategy
  APP_VERSION: 1.2.0-ondelete
  APP_VARIANT: statefulset

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

statefulset:
  updateStrategy:
    type: OnDelete
    partition: null
