replicaCount: 3

image:
  repository: luminitetime/devops-info-service-python
  tag: "lab09"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

env:
  APP_NAME: devops-info-service
  APP_DESCRIPTION: Helm-managed deployment
  APP_VERSION: 1.0.0-helm
  APP_VARIANT: primary

podAnnotations: {}

serviceAccount:
  create: true
  name: ""

secret:
  enabled: true
  name: ""
  data:
    username: helm-user
    password: helm-pass-123

vault:
  enabled: true
  role: devops-info-role
  secretPath: secret/data/devops-info/config
  injectFile: config.env
  template: |
    {{- with secret "secret/data/devops-info/config" -}}
    APP_USERNAME={{ .Data.data.username }}
    APP_PASSWORD={{ .Data.data.password }}
    APP_TOKEN={{ .Data.data.api_token }}
    {{- end -}}
  command: chmod 0444 /vault/secrets/config.env

securityContext:
  seccompProfile:
    type: RuntimeDefault
  runAsNonRoot: true
  runAsUser: 100
  runAsGroup: 101

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

revisionHistoryLimit: 5
minReadySeconds: 5

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
