replicaCount: 1

image:
  tag: "lab09"

env:
  APP_NAME: devops-info-service
  APP_DESCRIPTION: Development environment
  APP_VERSION: 1.0.0-dev
  APP_VARIANT: dev

service:
  type: NodePort
  nodePort: 30080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 5
